name: Tests
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: 📦 Install Dependencies
        run: yarn
      - name: 🏗 Build Project
        run: yarn build:dev
      - name: 🧪 Run Tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn test
